# Site settings
title: TZM Greece
tag_text: The Zeitgeist Movement Greece
description: The web site of TZM Greece
url: "http://zeitgeistmovement.gr"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
